### PR TITLE
Create new directory instead of echoing about it

### PR DESCRIPTION
**Pull request by arabar**
I wrote simple fix to pynote as @fergyfresh suggested.
Now the new directory for notes is created (alongside trash directory) and user shouldn't worry about it.

### CODE REVIEW

**Comment by arabar** [comment]
Fixed, working for me.

**Comment by arabar** [comment]
You were right about it. And now, it's a little bit faster :+1:

**Comment by rumpelsepp** [comment]
Nice. Would you mind squashing the commits into one? Then it is ready to merge. :+1: =)

**Comment by rumpelsepp** [comment]
Ahh and I think you have missed one call after your optimizations:

```diff
diff --git a/pynote/container.py b/pynote/container.py
index ae5a57f..8da99b3 100644
--- a/pynote/container.py
+++ b/pynote/container.py
@@ -1,5 +1,6 @@
 from datetime import datetime
 import json
+import os
 import os.path
 import re
 import unicodedata
@@ -23,7 +24,9 @@ def load_notes(path=config.DATA_PATH):
         return sorted(data, key=lambda n: n.age)
     else:
         error('The directory {} does not exist!'.format(path))
-        click.echo('You can create it with "mkdir {}".'.format(path))
+        click.echo('Creating new directory {}.'.format(path))
+        os.makedirs(format(path), 0o755)
+        os.makedirs(format(path) + '/.trash', 0o755)
         exit(1)
 ```

```diff
diff --git a/pynote/container.py b/pynote/container.py
index ae5a57f..c2eec4e 100644
--- a/pynote/container.py
+++ b/pynote/container.py
@@ -23,7 +23,9 @@ def load_notes(path=config.DATA_PATH):
         return sorted(data, key=lambda n: n.age)
     else:
         error('The directory {} does not exist!'.format(path))
-        click.echo('You can create it with "mkdir {}".'.format(path))
+        click.echo('Creating new directory {}.'.format(path))
+        path = config.TRASH_PATH
+        path.mkdir(parents=True)
         exit(1)
```
In your latest revision you just create the trash folder.

**Comment by arabar** [comment]
Yes, but it create trash folder recursively, so notes folder is created too.

**Comment by arabar** [comment]
https://docs.python.org/3/library/pathlib.html?highlight=pathlib#pathlib.Path.mkdir
>If parents is true, any missing parents of this path are created as needed (...)

There's also one thing in `config.py`
`TRASH_PATH = DATA_PATH / '.trash'`

So it's always created recursively. However, if in future trash path would be configurable then we have to add another `mkdir` function like I did it here:
```
path.mkdir(0o755)
path = config.TRASH_PATH
path.mkdir(0o755)
```

But I may be wrong :) I'm really new into Python and git, sorry for that.

**Comment by rumpelsepp** [comment]
> So it's always created recursively. However, if in future trash path would be configurable then we have to add another mkdir function like I did it here:

I see... Yeah that's right. :)

> But I may be wrong :) I'm really new into Python and git, sorry for that.

No problem. I could squash that stuff myself and just pick the metadata of your first commit, so that you are the actual author. :)

**Comment by arabar** [comment]
Thanks. It's nice to contribute to useful project and learn new things. I'll look forward to development of pynote and probably add something ;)

**Comment by rumpelsepp** [comment]
You are welcome to do this. :)

**Comment by rumpelsepp** [comment]
Applied in 0fcb6d0967c3edae2361331d08acc2014b46328c; thx. :)

**Pull request closed without merging**
